# Real Estate Price Prediction — CatBoost + scikit-learn Pipeline

> Предсказание цены жилья на данных Sberbank Russian Housing Market (Kaggle): кастомные трансформеры для очистки данных, CatBoostEncoder, PCA, подбор гиперпараметров через GridSearchCV.

In [1]:
import numpy as np
import pandas as pd

from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.pipeline import Pipeline, FeatureUnion

from sklearn.metrics import r2_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

import category_encoders as ce

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import GridSearchCV

import dill

from sklearn.base import BaseEstimator, TransformerMixin

import warnings
warnings.filterwarnings('ignore')

## Загрузка и обзор данных

In [2]:
# Загружаем данные Сбербанка по недвижимости: https://www.kaggle.com/c/sberbank-russian-housing-market/data
import os

path_name = "train.csv"

if not os.path.exists(path_name):
    # Автозагрузка через Kaggle API — требует настроенный ~/.kaggle/kaggle.json
    # (или переменные окружения KAGGLE_USERNAME / KAGGLE_KEY) и принятые правила
    # соревнования на странице Kaggle: https://www.kaggle.com/c/sberbank-russian-housing-market/rules
    import zipfile
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()
    api.competition_download_file("sberbank-russian-housing-market", "train.csv.zip")

    with zipfile.ZipFile("train.csv.zip", "r") as z:
        z.extractall(".")

df = pd.read_csv(path_name, sep=",")


In [3]:
# смотрим сведения о них
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30471 entries, 0 to 30470
Columns: 292 entries, id to price_doc
dtypes: float64(119), int64(157), object(16)
memory usage: 67.9+ MB


In [4]:
# выделяем целевую переменную
y = df["price_doc"]

In [5]:
# убираем "id", "price_doc" из набора признаков
X = df.drop(['id', 'price_doc'], axis=1)

## Кастомные трансформеры: пропуски и выбросы

In [6]:
# Обзор категориальных признаков
cat_names = []
for cat_colname in X.select_dtypes(include='object').columns:
    cat_names.append(cat_colname)

# Количество уникальных значений по каждому категориальному признаку —
# показывает кардинальность и обосновывает выбор CatBoostEncoder ниже
# (он хорошо работает с высококардинальными категориями, в отличие от one-hot)
X[cat_names].nunique().sort_values(ascending=False)


timestamp                    1161
sub_area                      146
ecology                         5
product_type                    2
culture_objects_top_25          2
thermal_power_plant_raion       2
incineration_raion              2
oil_chemistry_raion             2
radiation_raion                 2
railroad_terminal_raion         2
big_market_raion                2
nuclear_reactor_raion           2
detention_facility_raion        2
water_1line                     2
big_road1_1line                 2
railroad_1line                  2
dtype: int64

In [7]:
# Обзор численных признаков
num_names = []
for num_colname in X.select_dtypes(include='number').columns:
    num_names.append(num_colname)

print(f"Численных признаков: {len(num_names)}")


Численных признаков: 274


In [8]:
# делаем класс удаления тех колонок, в которых пропусков больше 20%

class empty_drop(BaseEstimator, TransformerMixin):
    def fit(self, x, y=None):
        dat = x.copy()
        self.lstRemCols = self._delemptCols(dat)
        return self
    
    def transform(self, x):        
        dat = x.copy()
        lstcols = list(set(dat.columns) - set(self.lstRemCols))
        return dat.loc[:, lstcols]
    
    def _delemptCols(self, df):
        emp_arr = []
        for i in df:
            pct_missing = np.mean(df[i].isnull())
            if (pct_missing != 0) and (pct_missing >= 0.2):
                emp_arr.append(i)        
        return emp_arr


In [9]:
# делаем класс устранения выбросов
class outlier_replace(BaseEstimator, TransformerMixin):
    def fit(self, x, y=None):
        dat = x.copy()
        self.lstRemCols = self._indicies_of_outliers(dat)
        return self
    
    def transform(self, x):        
        dat = x.copy()        
        for cat_colname in dat.columns:
            for array_of_index in self.lstRemCols:
                for i in array_of_index:
                    dat.loc[dat[cat_colname] == dat[cat_colname][i], cat_colname] = dat[cat_colname].median()
        return dat
    
    def _indicies_of_outliers(self, df):
        """Возвращает индекс выбросов, используя межквартильный размах
        """
        q1, q3 = np.percentile(df, [25,75])
        iqr = q3 - q1
        lower_bound = q1 - (iqr * 1.5)
        upper_bound = q3 + (iqr * 1.5)
        return np.where((df > upper_bound)|(df < lower_bound))    


In [10]:
# формируем пайплайн для численных признаков
numeric_transformer = Pipeline(steps=[
    ('emptdr',empty_drop()),
    ('outlier',outlier_replace()),
    ('imputer', SimpleImputer(strategy='median'))
    ])

## Кодирование признаков и снижение размерности (PCA)

In [11]:
# формируем пайплайн для категориальных признаков
categorical_transformer = ce.CatBoostEncoder(return_df=True)

In [12]:
# формируем пайплайн для всех признаков
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, cat_names),
        ('num', numeric_transformer, num_names)
        ])

In [13]:
# формируем результирующий пайплайн
mdl = Pipeline(steps=[('preprocessor', preprocessor),
                     ('scaler', StandardScaler()),
                      ('pca', PCA(n_components=0.98, whiten=True)),
                      ('catboost', CatBoostRegressor(learning_rate=0.1,depth=5,l2_leaf_reg=11,silent=True,random_state=42))])

In [14]:
#разделяем данные на тестовые и тренировочные
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Обучение модели и базовый результат

In [15]:
# тренируем модель и смотрим ее R^2
mdl.fit(x_train, y_train)
print(f"model score R^2: {mdl.score(x_test, y_test):.3f}")

model score R^2: 0.655


In [16]:
# Предсказываем значения (обрезаем снизу нулём — отрицательная цена недвижимости невозможна)
y_predict_ = np.clip(mdl.predict(x_test), 0, None)

In [17]:
# смотрим cреднеквадратичную логарифмическую ошибку регрессии
print(f"Средкв лог ошибка рег: {metrics.mean_squared_log_error(y_test,y_predict_):.3f}")

Средкв лог ошибка рег: 0.272


## Подбор гиперпараметров (GridSearchCV)

In [18]:
# задаем набор для отбора
param_grid = {
    'preprocessor__num__imputer__strategy': ['median'],    
'catboost__learning_rate': [0.1],
        'catboost__depth': [4, 6],
        'catboost__l2_leaf_reg': [11]}

grid_search = GridSearchCV(mdl, param_grid, cv=10)
grid_search

,estimator,Pipeline(step...ilent=True))])
,param_grid,"{'catboost__depth': [4, 6], 'catboost__l2_leaf_reg': [11], 'catboost__learning_rate': [0.1], 'preprocessor__num__imputer__strategy': ['median']}"
,scoring,None
,n_jobs,None
,refit,True
,cv,10
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,transformers,"[('cat', ...), ('num', ...)]"


In [19]:
# начинаем отбор лучших параметров модели
grid_search.fit(x_train, y_train)
print(f"Best params:")
print(grid_search.best_params_)

Best params:
{'catboost__depth': 6, 'catboost__l2_leaf_reg': 11, 'catboost__learning_rate': 0.1, 'preprocessor__num__imputer__strategy': 'median'}


In [20]:
# с учетом лучших отобранных параметров составляем пайплайн

numeric_transformer = Pipeline(steps=[
    ('emptdr',empty_drop()),
    ('outlier',outlier_replace()),
    ('imputer', SimpleImputer(strategy=grid_search.best_params_.get('preprocessor__num__imputer__strategy')))
    ])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_names),
        ('cat', categorical_transformer, cat_names)])

mdl2 = Pipeline(steps=[
                      ('preprocessor', preprocessor),
                    ('scaler', StandardScaler()),
                      ('pca', PCA(n_components=0.95, whiten=True)),
                      ('catboost', CatBoostRegressor(learning_rate=grid_search.best_params_.get('catboost__learning_rate'),
                                                     depth=grid_search.best_params_.get('catboost__depth'),
                                                     l2_leaf_reg=grid_search.best_params_.get('catboost__l2_leaf_reg'),
                                                    silent=True, random_state=42))])

## Итоговый результат

In [21]:
# тренируем модель на лучших параметрах
mdl2.fit(x_train, y_train)


,steps,"[('preprocessor', ...), ('scaler', ...), ...]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('num', ...), ('cat', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [22]:
# Предсказываем значения (обрезаем снизу нулём — отрицательная цена недвижимости невозможна)
y_predict_2 = np.clip(mdl2.predict(x_test), 0, None)

In [23]:
# смотрим R^2
print(f"R^2: {r2_score(y_test, y_predict_2):.3f}")

R^2: 0.656


In [24]:
# смотрим cреднеквадратичную логарифмическую ошибку регрессии
print(f"Средкв лог ошибка рег: {metrics.mean_squared_log_error(y_test, y_predict_2):.3f}")

Средкв лог ошибка рег: 0.231


In [25]:
# смотрим на пайплайн
mdl2.steps

[('preprocessor',
  ColumnTransformer(transformers=[('num',
                                   Pipeline(steps=[('emptdr', empty_drop()),
                                                   ('outlier', outlier_replace()),
                                                   ('imputer',
                                                    SimpleImputer(strategy='median'))]),
                                   ['full_sq', 'life_sq', 'floor', 'max_floor',
                                    'material', 'build_year', 'num_room',
                                    'kitch_sq', 'state', 'area_m', 'raion_popul',
                                    'green_zone_part', 'indust_part',
                                    'children_preschool', 'preschool_quota',
                                    'pres...
                                    'full_all', 'male_f', ...]),
                                  ('cat', CatBoostEncoder(),
                                   ['timestamp', 'product_type', 'sub_area

In [26]:
# сериализуем пайплайн
with open("catboost_pipeline2.dill", "wb") as f:
    dill.dump(mdl2, f)
    

## Выводы

- Итоговая модель (CatBoost в пайплайне с кастомной обработкой пропусков/выбросов, CatBoostEncoder и PCA) показывает R² = 0.656, RMSLE = 0.231 на тестовой выборке.

- Подбор гиперпараметров через GridSearchCV (10-фолд кросс-валидация) дал наибольший эффект именно по целевой метрике соревнования — RMSLE снизилась с 0.272 до 0.231 (~15% относительного улучшения), при этом R² почти не изменился (0.655 → 0.656).

- Это объяснимо разной чувствительностью метрик: R² сильнее зависит от абсолютного масштаба цен и от дорогих объектов, тогда как RMSLE (официальная метрика соревнования) оценивает относительную ошибку — и именно на неё повлияла настройка гиперпараметров. Вывод: ориентироваться стоит на метрику, релевантную задаче, а не только на общие показатели вроде R² — улучшение, незаметное в одной метрике, может быть существенным в другой.